#!/bin/bash

echo -e "$REDCOLOR testing post checkout $NOCOLOR"
echo -e "$PINKCOLOR testing post checkout $NOCOLOR"
echo -e "$BLUECOLOR testing post checkout $NOCOLOR"
echo -e "$GREENCOLOR testing post checkout $NOCOLOR"
echo -e "$YELLOWCOLOR testing post checkout $NOCOLOR"
